Repository zuhebahmed88091/tour_savvy_backend, pull requests merged in 2023-11, with the labels that each got.

#39 Update user controller for Login and Logout in frontend
  app/controllers/application_controller.rb
  app/controllers/current_user_controller.rb
  config/routes.rb
Labels: enhancement, Team Review

#40 Update current user controller for registration
  app/controllers/current_user_controller.rb
  config/routes.rb
Labels: enhancement, Team Review

#41 Add reservation details
  app/controllers/application_controller.rb
  app/controllers/packages_controller.rb
  app/controllers/reservations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users_controller.rb
  config/routes.rb
  db/migrate/20231027143602_devise_create_users.rb
  db/schema.rb
Labels: Team Review

#46 API Documentation
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/packages_controller.rb
  app/controllers/reservations_controller.rb
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/factories/packages.rb
  spec/factories/users.rb
  spec/integration/api/packages_spec.rb
  spec/integration/api/reservations_spec.rb
  spec/packages_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation

#47 Testing
  app/models/package.rb
  app/models/reservation.rb
  app/models/user.rb
  spec/models/package_spec.rb
  spec/models/reservation_spec.rb
  spec/models/user_spec.rb
Labels: Team Review
